version: '3.3'

services:

    php:
        container_name: runopencode_event_overlaps_test
        build:
            context: './'
            args:
                X_DEBUG_HOST:   ${X_DEBUG_HOST}
                X_DEBUG_PORT:   ${X_DEBUG_PORT}
                X_DEBUG_IDEKEY: ${X_DEBUG_IDEKEY}
        env_file:
            -   .env
        volumes:
            -  './:/var/www/html'
            - '${HOME}/.phive:${HOME}/.phive'
